In [4]:
import torch
import numpy as np

src = torch.from_numpy(np.arange(1, 11)).float().view(2, 5)
#tensor([[ 1.,  2.,  3.,  4.,  5.],
#        [ 6.,  7.,  8.,  9., 10.]])

input_tensor = torch.zeros(3, 5)
#tensor([[0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0.]])

index_tensor = torch.tensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]])
#tensor([[0, 1, 2, 0, 0],
#         [2, 0, 0, 1, 2]]) 

input_tensor.scatter_(0, index_tensor, 100)
  #tensor([[ 1.,  7.,  8.,  4.,  5.],
  #        [ 0.,  2.,  0.,  9.,  0.],
  #        [ 6.,  0.,  3.,  0., 10.]])


tensor([[100., 100., 100., 100., 100.],
        [  0., 100.,   0., 100.,   0.],
        [100.,   0., 100.,   0., 100.]])