In [3]:
import numpy as np

In [17]:
v = np.arange(27).reshape((3,3,3))

In [18]:
v

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
v[:,:,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [20]:
v[...,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [21]:
v[:,0]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])