In [2]:
import numpy as np

A = np.diag([1.0, 2, 3])

np.flipud(A)


array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

In [5]:
A[::-1,...]

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

In [6]:
A[::-1]

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

In [3]:
os.path.realpath("avatar.png")

'C:\\Users\\cassi\\avatar.png'

In [9]:
print("\n123\n\n".strip())

123


In [23]:
import gradio as gr
import os
import time

# Chatbot demo with multimodal input (text, markdown, LaTeX, code blocks, image, audio, & video). Plus shows support for streaming text.


def print_like_dislike(x: gr.LikeData):
    print(x.index, x.value, x.liked)


def add_text(history, text):
    history = history + [(text, None)]
    return history, gr.Textbox(value="", interactive=False)


def add_file(history, file):
    print(file.name)
    history = history + [((file.name,), None)]
    return history


def bot(history):
    response = "**That's cool!**"
    history[-1][1] = (r'C:\Users\cassi\AppData\Local\Temp\gradio\b0d08f12e5c72d4a9e32d4609e16428713059009\avatar.png',)
    history += [[None, '']]
    
    for character in response:
        history[-1][1] += character
        
        yield history

# def bot_image(history):
#     history += [(None, (r'C:\Users\cassi\AppData\Local\Temp\gradio\b0d08f12e5c72d4a9e32d4609e16428713059009\avatar.png', None))]
#     return history


with gr.Blocks() as demo:
    chatbot = gr.Chatbot(
        [],
        elem_id="chatbot",
        bubble_full_width=False,
        avatar_images=(None, (os.path.realpath("avatar.png"))),
    )

    with gr.Row():
        txt = gr.Textbox(
            scale=4,
            show_label=False,
            placeholder="Enter text and press enter, or upload an image",
            container=False,
        )
        btn = gr.UploadButton("📁", file_types=["image", "video", "audio"])

    txt_msg = txt.submit(add_text, [chatbot, txt], [chatbot, txt], queue=False).then(
        bot, chatbot, chatbot, api_name="bot_response"
    )
    
    txt_msg.then(lambda: gr.Textbox(interactive=True), None, [txt], queue=False)
    file_msg = btn.upload(add_file, [chatbot, btn], [chatbot], queue=False).then(
        bot, chatbot, chatbot
    )

    chatbot.like(print_like_dislike, None, None)


demo.queue()
demo.launch()


Running on local URL:  http://127.0.0.1:7874

To create a public link, set `share=True` in `launch()`.


In [2]:
import gradio as gr
class Demo(gr.Blocks):
    def __init__(self, title, css=None, theme=None):
        super().__init__(title=title, css=css, theme=theme)
        # INPUTS
        self.audio = gr.Audio(
            type="filepath",
            label="Загрузка аудиофайла или запись с микрофона",
            interactive=True,
            container=True,
        )

        self.examples = {
            "examples": [
                ["assets/1.m4a"]
            ],
            "inputs": self.audio
        }

        with self:
            with gr.Row():
                with gr.Column(scale=2):
                    self.audio.render()
                    ex = gr.Examples(**self.examples)
# Запуск
demo = Demo(title="")
demo.launch(share=False)


Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.


c:\Users\el1ja\anaconda3\Lib\site-packages\gradio\analytics.py:106: UserWarning: IMPORTANT: You are using gradio version 4.42.0, however version 4.44.1 is available, please upgrade. 
--------
  warnings.warn(


In [13]:
import gradio as gr

with gr.Blocks() as demo:
    h1 = gr.HighlightedText({"text": 'Hello Tom', "entities": [{'start' : 0, 'end' : 5, 'entity' : 'I-PER'}]})
demo.launch()

Running on local URL:  http://127.0.0.1:7863

To create a public link, set `share=True` in `launch()`.


In [3]:
#!pip install gradio

In [2]:
ner_pipeline("Tom Sowyaer from America")

[{'entity': 'I-PER',
  'score': 0.9995932,
  'index': 1,
  'word': 'Tom',
  'start': 0,
  'end': 3},
 {'entity': 'I-PER',
  'score': 0.99941874,
  'index': 2,
  'word': 'So',
  'start': 4,
  'end': 6},
 {'entity': 'I-PER',
  'score': 0.9790755,
  'index': 3,
  'word': '##wy',
  'start': 6,
  'end': 8},
 {'entity': 'I-PER',
  'score': 0.8932993,
  'index': 4,
  'word': '##ae',
  'start': 8,
  'end': 10},
 {'entity': 'I-PER',
  'score': 0.9906557,
  'index': 5,
  'word': '##r',
  'start': 10,
  'end': 11},
 {'entity': 'I-LOC',
  'score': 0.9997644,
  'index': 7,
  'word': 'America',
  'start': 17,
  'end': 24}]

In [1]:
from transformers import pipeline

import gradio as gr

ner_pipeline = pipeline("ner")

examples = [
    "Does Chicago have any stores and does Joe live here?",
]

def ner(text):
    output = ner_pipeline(text)
    return {"text": text, "entities": output}

demo = gr.Interface(ner,
             gr.Textbox(placeholder="Enter sentence here..."),
             gr.HighlightedText(),
             examples=examples)

demo.launch()

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Hardware accelerator e.g. GPU is

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
